package com.example.restservicedemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.restservicedemo.domain.Car;
import com.example.restservicedemo.domain.Person;

public class CarManager {

	private Connection connection;

	private static final String URL = "jdbc:hsqldb:hsql://localhost/workdb";
	private static final String CREATE_TABLE_CAR = "CREATE TABLE Car(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, make varchar(20),model varchar(20), yop integer)";

	private PreparedStatement addCarStmt;
	private PreparedStatement deleteAllCarsStmt;
	private PreparedStatement getAllCarsStmt;
	private PreparedStatement getAllPersonCarsStmt;
	private PreparedStatement getCarByIdStmt;

	private Statement statement;

	public CarManager() {
		try {
			connection = DriverManager.getConnection(URL);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Car".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(CREATE_TABLE_CAR);

			addCarStmt = connection
					.prepareStatement("INSERT INTO Car (make, model, yop) VALUES (?, ?, ?)");
			deleteAllCarsStmt = connection
					.prepareStatement("DELETE FROM Car");
			getAllCarsStmt = connection
					.prepareStatement("SELECT id, make, model, yop FROM Car");
			getAllPersonCarsStmt = connection
					.prepareStatement("SELECT  id, make, model, yop FROM CarPerson LEFT JOIN Car ON CarPerson.id_car=Car.id WHERE id_person = ?");
			getCarByIdStmt = connection
					.prepareStatement("SELECT id, make, model, yop FROM Car where id = ?");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}

	void clearCars() {
		try {
			deleteAllCarsStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public int addCar(Car car) {
		int count = 0;
		try {
			addCarStmt.setString(1, car.getMake());
			addCarStmt.setString(2, car.getModel());
			addCarStmt.setInt(3, car.getYop());

			count = addCarStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

	public List<Car> getAllCars() {
		List<Car> cars = new ArrayList<Car>();

		try {
			ResultSet rs = getAllCarsStmt.executeQuery();

			while (rs.next()) {
				Car p = new Car();
				p.setId(rs.getInt("id"));
				p.setMake(rs.getString("make"));
				p.setModel(rs.getString("model"));
				p.setYop(rs.getInt("yop"));
				cars.add(p);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return cars;
	}
	
	public List<Car> getAllPersonCars(long id) {
		List<Car> cars = new ArrayList<Car>();

		try {
			getAllPersonCarsStmt.setLong(1, id);
			ResultSet rs = getAllPersonCarsStmt.executeQuery();

			while (rs.next()) {
				Car p = new Car();
				p.setId(rs.getInt("id"));
				p.setMake(rs.getString("make"));
				p.setModel(rs.getString("model"));
				p.setYop(rs.getInt("yop"));
				cars.add(p);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return cars;
	}

	public Car getCar(Long id) {
		Car p = new Car();
		try {
			getCarByIdStmt.setLong(1, id);
			ResultSet rs = getCarByIdStmt.executeQuery();

			while (rs.next()) {
				p.setId(rs.getInt("id"));
				p.setMake(rs.getString("make"));
				p.setModel(rs.getString("model"));
				p.setYop(rs.getInt("yop"));
				break;
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		return p;
	}

}
