package com.example.restservicedemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.restservicedemo.domain.Car;
import com.example.restservicedemo.domain.CarPerson;
import com.example.restservicedemo.domain.Person;

public class CarPersonManager {

	private Connection connection;

	private static final String URL = "jdbc:hsqldb:hsql://localhost/workdb";
	private static final String CREATE_TABLE_CAR = "CREATE TABLE CarPerson(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_car bigint, id_person bigint, FOREIGN KEY (id_car) REFERENCES Car(Id),FOREIGN KEY (id_person) REFERENCES Person(Id))";

	private PreparedStatement sellCarPerson;

	private Statement statement;

	public CarPersonManager() {
		try {
			connection = DriverManager.getConnection(URL);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("CarPerson".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(CREATE_TABLE_CAR);

			sellCarPerson = connection
					.prepareStatement("INSERT INTO CarPerson (id_car, id_person) VALUES (?, ?)");
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}


	public int sellCarPerson(CarPerson carPerson) {
		int count = 0;
		try {
			sellCarPerson.setInt(1, carPerson.getId_Car());
			sellCarPerson.setInt(2, carPerson.getId_Person());

			count = sellCarPerson.executeUpdate();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

}
